AllCops:
  Include:
    - 'Gemfile'
    - 'app/**/*.rb'
    - 'config/**/*.rb'
  Exclude:
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'lib/tasks/*'
    - 'features/**/*.rb'
    - 'script/**/*.rb'
    - 'vendor/**/*'

Style/SelfAssignment: # good to be enabled
  Enabled: false

Style/GlobalVars: # good to be enabled
  Enabled: false

Style/NestedTernaryOperator: # good to be enabled
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/BlockNesting: # good to be enabled
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false
