defaults: &defaults
  adapter: sqlite3
  pool: 5
  encoding: utf8
  timeout: 5000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3

cucumber:
  <<: *defaults
