default: &default
  gmap_api_key: <%= ENV['GMAP_API_KEY'] %>
  gmap_static_maps_api_key: <%= ENV['GMAP_STATIC_MAPS_API_KEY'] %>
  open_weather_api_key: <%= ENV['OPEN_WEATHER_API_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  <<: *default

test:
  <<: *default
  secret_key_base: c3985a65bb0949258b8c6b92dd098086fbbca3d19726e27e680989ab9a7d118264ae0e618981d51280ee2e98ce17fb7e5d61395374603438b64bec245fecc8be

production:
  <<: *default
