default: &default
  gmap_api_key: <%= ENV['GMAP_API_KEY'] %>
  gmap_static_maps_api_key: <%= ENV['GMAP_STATIC_MAPS_API_KEY'] %>
  open_weather_api_key: <%= ENV['OPEN_WEATHER_API_KEY'] %>

development:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
